pipeline {
 agent any
 stages {
 stage ('Checkout') {
 steps {
 git branch:'master', url: 'https://github.com/OWASP/Vulnerable-WebApplication.git'
 }
 }

 stage('Code Quality Check via SonarQube') {
 steps {
 script {
 def scannerHome = tool 'SonarQube';
 withSonarQubeEnv('SonarQube') {
 sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=OWSAP -Dsonar.sources=. -Dsonar.sources=. -Dsonar.host.url=http://localhost:9000 -Dsonar.login=fa142b6fd53aadc0ecc713c14872d8903ed2cb65"
 }
 }
 }
 }
 }
 post {
 always {
 recordIssues enabledForFailure: true, tool: sonarQube()
 }
 }
}